server:
  port: 8093
spring:
  application:
    name: todo-service
  data:
    mongodb:
      database: todolist
      uri: mongodb://localhost:27017
  error:
    include-message: always

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate=DEBUG: