server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-todo-list?createDatabaseIfNotExist=true
    username: root
    password: Bismillah@123

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  jwt:
    expiration:
      time: 360000000000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
